language: node_js
node_js:
- '11'
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: npm
  email: quentin@frontapp.com
  api_key:
    secure: n+9ka3RQyqhmEi/H+oDu9UvS0mpkVJnuuKCVGndDiw8Mi1Jhi1sFMwzIQA6i+Uc0p552hueVil74vB4/GPVqRZ2brkdEifTFtougUphjMDIVYDYtfVFSHjNzE/Zh55LYh7ltqYaEcf5QLh3JuCryLfsXBW0EKCrRMUQF1yROvWyMdWnH/KMGN/I5PLUD9kKGU6z63vKe0gDxHVbidUaJNQLz2fRLOgkiSRyzO1Xs5mTwLgFYtAXvwNX4uV1hl0x0YSVPhQgTFuUHxqDIYMcO4kddK9MhYdtoNrxdob/nT+Ov0whtnGtrvi9ZMKFp6ZbH+nWAdNX6tfjzAfy3GB+AkZjAFGvmXtOACONu01XWbs+xhVdmLA7QA/imEy9etalFSmnpzO1i6BDAVGboIJgeyl9jW+Ycq89I6yoaYubjUisPt0Ubz+TLoAq/K/y80WshWYVY5SdFOQh0ZcFvbPAQ05nQyHLFQDBygG0ukIJv0Ef6oEStu43e8j5owMlwXyyfgCDy6AupRdv9GfydCXRHfQWG9lzC1Os/97vxjc1YpVinEsYOH0U819w4OV3kUacdbHFEUo+4A15cD9axsTVg0mx7TodjfVSG7laJxfPhvt73EzyJYzP8bJT6OfEtxPYkE8H9Exs5TWlDFvDWDnA0akGqZSOxrlQESEWIGRj77u4=
  on:
    repo: quentez/talonjs
    tags: true
    branch: master
